import type { Product, Sale } from '$lib/types/index';

const now = new Date();

const isoDaysAgo = (days: number, hour = 10, minute = 15): string => {
  const value = new Date(now);
  value.setDate(value.getDate() - days);
  value.setHours(hour, minute, 0, 0);
  return value.toISOString();
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prd-001',
    itemCode: 'BEV-001',
    name: 'Premium Coffee Mix',
    nameMy: 'ကော်ဖီမစ်',
    barcode: '899100000001',
    category: 'drinks',
    unit: 'PCS',
    costPrice: 850,
    sellingPrice: 1200,
    stock: 48,
    reorderLevel: 10,
    icon: 'coffee',
  },
  {
    id: 'prd-002',
    itemCode: 'SNK-001',
    name: 'Sea Salt Crackers',
    nameMy: 'ဆားသုံးခရက်ကာ',
    barcode: '899100000002',
    category: 'snacks',
    unit: 'PCS',
    costPrice: 600,
    sellingPrice: 900,
    stock: 22,
    reorderLevel: 8,
    icon: 'cracker',
  },
  {
    id: 'prd-003',
    itemCode: 'HOM-001',
    name: 'Dishwashing Liquid',
    nameMy: 'ပန်းကန်ဆေးရည်',
    barcode: '899100000003',
    category: 'household',
    unit: 'BTL',
    costPrice: 1400,
    sellingPrice: 1900,
    stock: 7,
    reorderLevel: 6,
    icon: 'bottle',
  },
  {
    id: 'prd-004',
    itemCode: 'FOD-001',
    name: 'Butter Croissant',
    nameMy: 'ထောပတ်ခရိုဆန်',
    barcode: '899100000004',
    category: 'food',
    unit: 'PCS',
    costPrice: 900,
    sellingPrice: 1500,
    stock: 18,
    reorderLevel: 5,
    icon: 'croissant',
  },
  {
    id: 'prd-005',
    itemCode: 'FOD-002',
    name: 'Chicken Curry Rice',
    nameMy: 'ကြက်သားဟင်းထမင်း',
    barcode: '899100000005',
    category: 'food',
    unit: 'BOX',
    costPrice: 2100,
    sellingPrice: 3200,
    stock: 11,
    reorderLevel: 4,
    icon: 'rice',
  },
  {
    id: 'prd-006',
    itemCode: 'BEV-002',
    name: 'Sparkling Soda',
    nameMy: 'ဆိုဒါ',
    barcode: '899100000006',
    category: 'drinks',
    unit: 'CAN',
    costPrice: 700,
    sellingPrice: 1100,
    stock: 54,
    reorderLevel: 12,
    icon: 'soda',
  },
  {
    id: 'prd-007',
    itemCode: 'PER-001',
    name: 'Travel Tissue Pack',
    nameMy: 'တစ်ရှူးထုပ်',
    barcode: '899100000007',
    category: 'personal',
    unit: 'PK',
    costPrice: 350,
    sellingPrice: 550,
    stock: 9,
    reorderLevel: 10,
    icon: 'tissue',
  },
  {
    id: 'prd-008',
    itemCode: 'STA-001',
    name: 'Thermal Receipt Roll',
    nameMy: 'Receipt Roll',
    barcode: '899100000008',
    category: 'stationery',
    unit: 'ROLL',
    costPrice: 500,
    sellingPrice: 850,
    stock: 5,
    reorderLevel: 6,
    icon: 'roll',
  },
  {
    id: 'prd-009',
    itemCode: 'SNK-002',
    name: 'Honey Peanuts',
    nameMy: 'ပျားရည်မြေပဲ',
    barcode: '899100000009',
    category: 'snacks',
    unit: 'PCS',
    costPrice: 650,
    sellingPrice: 1000,
    stock: 27,
    reorderLevel: 9,
    icon: 'peanut',
  },
  {
    id: 'prd-010',
    itemCode: 'OTH-001',
    name: 'Gift Bag Medium',
    nameMy: 'လက်ဆောင်အိတ်',
    barcode: '899100000010',
    category: 'other',
    unit: 'PCS',
    costPrice: 400,
    sellingPrice: 750,
    stock: 13,
    reorderLevel: 5,
    icon: 'bag',
  },
];

export const MOCK_SALES: Sale[] = [
  {
    id: 1,
    saleNumber: 'SAL-20260421-001',
    saleDate: isoDaysAgo(0, 9, 12),
    customerName: 'Walk-in Customer',
    totalAmount: 5400,
    taxAmount: 0,
    discountAmount: 200,
    netAmount: 5200,
    paymentMethod: 'CASH',
    status: 'COMPLETED',
  },
  {
    id: 2,
    saleNumber: 'SAL-20260421-002',
    saleDate: isoDaysAgo(0, 11, 48),
    customerName: 'May Thidar',
    totalAmount: 8600,
    taxAmount: 0,
    discountAmount: 600,
    netAmount: 8000,
    paymentMethod: 'CARD',
    status: 'COMPLETED',
  },
  {
    id: 3,
    saleNumber: 'SAL-20260421-003',
    saleDate: isoDaysAgo(0, 14, 5),
    customerName: 'Downtown Office',
    totalAmount: 12400,
    taxAmount: 0,
    discountAmount: 400,
    netAmount: 12000,
    paymentMethod: 'CREDIT',
    status: 'COMPLETED',
  },
  {
    id: 4,
    saleNumber: 'SAL-20260420-004',
    saleDate: isoDaysAgo(1, 10, 22),
    customerName: 'Office Pantry',
    totalAmount: 5700,
    taxAmount: 0,
    discountAmount: 200,
    netAmount: 5500,
    paymentMethod: 'TRANSFER',
    status: 'COMPLETED',
  },
  {
    id: 5,
    saleNumber: 'SAL-20260420-005',
    saleDate: isoDaysAgo(1, 16, 37),
    customerName: 'Aye Chan',
    totalAmount: 3000,
    taxAmount: 0,
    discountAmount: 0,
    netAmount: 3000,
    paymentMethod: 'CASH',
    status: 'COMPLETED',
  },
  {
    id: 6,
    saleNumber: 'SAL-20260419-006',
    saleDate: isoDaysAgo(2, 13, 14),
    customerName: 'Neighborhood Mart',
    totalAmount: 9100,
    taxAmount: 0,
    discountAmount: 300,
    netAmount: 8800,
    paymentMethod: 'TRANSFER',
    status: 'COMPLETED',
  },
  {
    id: 7,
    saleNumber: 'SAL-20260418-007',
    saleDate: isoDaysAgo(3, 12, 9),
    customerName: 'Walk-in Customer',
    totalAmount: 1900,
    taxAmount: 0,
    discountAmount: 0,
    netAmount: 1900,
    paymentMethod: 'CARD',
    status: 'COMPLETED',
  },
  {
    id: 8,
    saleNumber: 'SAL-20260417-008',
    saleDate: isoDaysAgo(4, 18, 3),
    customerName: 'Loyalty Member',
    totalAmount: 7450,
    taxAmount: 0,
    discountAmount: 450,
    netAmount: 7000,
    paymentMethod: 'CASH',
    status: 'COMPLETED',
  },
];
